import { Provider } from 'jotai'
import { type Metadata } from 'next'
import { Inter } from 'next/font/google'

import { cn } from '@/src/lib/utils'

import Sidebar from '../components/sidebar'
import './globals.css'

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen font-sans antialiased bg-black overflow-hidden h-lvh',
          fontSans.variable
        )}
      >
        <Provider>
          <Sidebar />
          {modal}
          {children}
        </Provider>
      </body>
    </html>
  )
}
